#!/bin/bash

#SchemeRealizer - A free ORM and Translator for Diagrams, Databases and PHP-Classes/Interfaces.
#Copyright (C) 2016  Michael Watzer

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.

#You should have received a copy of the GNU Affero General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

#@author   Michael Watzer
#@version  1.0
#@since    19.03.2017
#@category Find all files where the argument occurs

###############################################################################
### Declare variables
###############################################################################

work=~/workspace/SchemeRealizer

###############################################################################
### Declare functions
###############################################################################

#@category get usage
#@param    crash 1(true)||0(false)
function usage {
  echo "usage: findme <foo-bar>"
  if [ $1 -eq 1 ]; then
    exit $1
  fi
}

###############################################################################
### Main
###############################################################################

if [ -z $1 ]; then
  echo "argument missing!"
  usage 1;
fi

if [ ! -d $work ]; then
  echo "directory $work not found!"
  usage 1;
fi

find $work -type f -exec grep -li $1 {} \; -print

exit 0
