CREATE TABLE Event(
	db INT(11) NULL AUTO_INCREMENT,
	name INT(11) NOT NULL,
	body INT(11) NULL,
	definer INT(11) NOT NULL,
	execute_at INT(11) NULL,
	interval_value INT(11) NOT NULL,
	interval_field INT(11) NOT NULL,
	created INT(11) NOT NULL,
	modified INT(11) NULL,
	last_executed INT(11) NOT NULL,
	starts INT(11) NOT NULL,
	ends INT(11) NULL,
	status INT(11) NOT NULL,
	on_completion INT(11) NOT NULL,
	sql_mode INT(11) NULL,
	comment INT(11) NULL,
	originator INT(11) NULL,
	time_zone INT(11) NULL,
	character_set_client INT(11) NOT NULL,
	collation_connection INT(11) NULL,
	db_collation INT(11) NULL,
	body_utf8 INT(11) NOT NULL,
	UNIQUE (definer,execute_at,on_completion,sql_mode,character_set_client,db_collation),
	PRIMARY KEY (db,body),
	KEY name (name),
	KEY interval_value (interval_value),
	KEY interval_field (interval_field),
	KEY created (created),
	KEY modified (modified),
	KEY last_executed (last_executed),
	KEY comment (comment),
	KEY originator (originator),
	KEY time_zone (time_zone)
)
