CREATE TABLE Event(
	db INTEGER PRIMARY KEY AUTOINCREMENT NULL,
	name INT NULL,
	body INT NULL,
	definer INT NOT NULL,
	execute_at INT NOT NULL,
	interval_value INT NULL,
	interval_field INT NOT NULL,
	created INT NOT NULL,
	modified INT NULL,
	last_executed INT NOT NULL,
	starts INT NULL,
	ends INT NULL,
	status INT NOT NULL,
	on_completion INT NOT NULL,
	sql_mode INT NOT NULL,
	comment INT NOT NULL,
	originator INT NULL,
	time_zone INT NOT NULL,
	character_set_client INT NULL,
	collation_connection INT NULL,
	db_collation INT NULL,
	body_utf8 INT NOT NULL,
	UNIQUE (name,definer,execute_at,created,last_executed,on_completion,sql_mode,originator,time_zone,character_set_client,db_collation,body_utf8)
)
